services:
  mongo:
    image: mongo:8.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: shopping-cart
    volumes:
      - mongo_data:/data/db

  app:
    image: shopping-cart-app:latest
    container_name: shopping-cart
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/shopping-cart

volumes:
  mongo_data: